# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  registryServiceConnection: CinemaHub_ARC
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6e4706a8-bf24-4bf3-8218-40d583c1148a'
  imageRepository: 'cinemahub'
  containerRegistry: 'cinemahub.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/CinemaHub/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Container registry login
      inputs:
        command: login
        containerRegistry: $(registryServiceConnection)
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
